### ISSUE TITLE
Previous and Next buttons on MID is not working

### ISSUE THREAD

**Issue by vgergiev** [tedsalmon/BlueBus#41]
After update with moving to TEL UI buttons, which are on MID, are not switching the tracks.
The buttons on the wheel are working well, without any issues.

It seems that BlueBus is not listening for commands issues by these buttons.

![image](https://user-images.githubusercontent.com/13521069/95882521-77197a00-0d82-11eb-8f1a-8052e9213403.png)
(Photo from internet)

Probably it can affect those guys who don't have media buttons on the wheel.

**Comment by piersholt** [comment]
If a button has multiple use cases the BMBT will address a specific device rather than broadcasting a button message. I gather the MID is similar in this respect.

I'd guess the button message handler needs to be updated accordingly. I'll check it later today.

**Comment by tedsalmon** [comment]
@vgergiev,

This has been fixed in the newest build (code hasn't been pushed up because... reasons?) https://t3ddftw.s3.us-east-2.amazonaws.com/BlueBus/firmware/bluebus_1_1_15_9.hex

When I switched to the TEL UI handler, the RAD stopped sending the CDC the "Next Track" and "Previous Track" commands. I had not been listening to the physical button press messages before this change, so I had to add a new event.

Thanks!
-Ted
