### ISSUE TITLE
Feature Request: Force Audio Protocol

### ISSUE THREAD

**Issue by QSSaber** [tedsalmon/BlueBus#42]
Feature request for implementation of forced bluetooth audio codec. 

On bluebus.dev, there are list of different mobile devices that does not work seamlessly with BlueBus. Most of them are due to the wrong bluetooth codec, and it was a common issue for those phones. 

Most of the cases, A2DP profile would use SBC codec to send over audio as it is such a commonly supported codec. The Sierra Wireless BC127 module even supports aptX which would be considered ideal for use for Samsung devices equipped with Qualcomm Snapdragon APs. 
c.f. Enforcing an unsupported codec may CAUSE connectivity issues. But Sierra Wireless already built that into the firmware to have SBC codec to be used as a fallback. 

Samsung devices have forced bluetooth audio codec setting under the Developer Options menu, however. Yet, the support setting of the receiver module takes priority over the sender. 

Allowing users to select bluetooth audio codec would solve with connectivity, volume control, and audio quality issues. 
Please consider the following codec to be supported: SBC, AAC, and aptX.

**Comment by tedsalmon** [comment]
Hi @QSSaber,

Thanks for your feedback!

A few things --

1. The A2DP codec in use does not impact the quality of the connection. The fact of the matter is that the Samsung devices listed simply have a low RSSI at very short distances, likely due to a low TX power defined in the device driver. While certain codecs may perform better under low SNR conditions, this is only to do with the fact that they are better compressed and can hold their own even when frames are constantly having to be resent. If we were to look at it from an OSI perspective, the codec would sit around L3, while the physical bluetooth protocol sits on L1/L2.

1. The BlueBus already makes use of the AAC protocol by default (https://github.com/tedsalmon/BlueBus/blob/master/firmware/application/upgrade.c#L41) -- See 
![Screenshot_20201019_113608](https://user-images.githubusercontent.com/4956562/96539646-9411e980-1269-11eb-94d0-9d53a4f20750.png)

1. aptX et al. is marketing wank, for the most part. Sure, it ads some measurable quality to _certain_ audio streams under certain conditions, but that's not  valuable for a system intended to be used in vehicles that are at least ten years old and equipped with electronics designed in the 1990s. Not only that, but I would have to put myself in a position where I would have to purchase modules with a lead time, since the `-HD` part is not really stocked in any good quantities by Sierra Wireless distributors. It's also more expensive because of the license fees imposed by Qualcomm.

Thanks!
-Ted
